{
  "model": "dhost-ref",
  "kernels": {
    "K": [
      [
        1,
        0.1
      ],
      [
        0.1,
        1
      ]
    ],
    "G": [
      [
        1,
        0
      ],
      [
        0,
        1
      ]
    ]
  }
}
