{
  "model": "gr-flat",
  "kernels": {
    "K": [
      [
        1,
        0
      ],
      [
        0,
        1
      ]
    ],
    "G": [
      [
        1,
        0
      ],
      [
        0,
        1
      ]
    ]
  }
}
